CREATE TABLE MESSAGE
(
    ID           BIGINT AUTO_INCREMENT PRIMARY KEY,
    BODY         CLOB,
    CREATED_DATE TIMESTAMP,
    CLIENT_ID BIGINT,
    CONSTRAINT FK_CLIENT_MESSAGE FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS (ID)
);