CREATE TABLE CLIENTS
(
    ID           BIGINT AUTO_INCREMENT PRIMARY KEY,
    LOGIN        VARCHAR(255) NOT NULL,
    LAST_NAME    VARCHAR(255) NOT NULL,
    FIRST_NAME   VARCHAR(255) NOT NULL,
    MIDDLE_NAME  VARCHAR(255),
    BIRTH_DATE   DATE NOT NULL,
    CREATED_DATE TIMESTAMP,
    UPDATED_DATE TIMESTAMP,

    UNIQUE (LOGIN)
);
